version: '3.7'
services:
  frontend:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`site.com`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
    image: frontend-image 
    environment:
      REACT_APP_GQL_URL: https://api.site.com/graphql
      PORT: 3000
    expose:
      - 3000
  
  backend: 
    expose: 
      - 5000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.site.com`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
    image: backend-image
    environment:
      POSTGRAPHILE_PORT: 5000
    
  traefik:
    image: traefik:latest
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - "443:443"
    depends_on:
      - frontend
      - backend

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: dfasdff31
      POSTGRES_USER: origin
    ports:
      - 5432