version: '3.3'
services:
  devcontainer-backend: 
    image: ghcr.io/brandonsimon1/devpod-node:62b026944e7208fcce86514aa7475cdd273edba4 
    environment:
      - SSH_PRIVATE_KEY
      - REPO_URL=git@github.com:OriginGG/NewOriginBackend.git
      - NODE_VERSION
      - NAME
      - EMAIL
      - PGPASSWORD=dfasdff31
      - PGUSER=origin
      - PGDATABASE=origin
      - PGHOST=postgres
      - PGSCHEMA=graphile
      - POSTGRAPHILE_PORT=5000
    ports: 
      - 5000:5000

  devcontainer-frontend: 
    image: ghcr.io/brandonsimon1/devpod-node:62b026944e7208fcce86514aa7475cdd273edba4 
    environment:
      - SSH_PRIVATE_KEY
      - REPO_URL=git@github.com:OriginGG/NewOriginFrontend.git
      - NODE_VERSION
      - NAME
      - EMAIL
      - GRAPHQL_URI=http://devcontainer-backend/graphql
    ports:
      - 3000:3000

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: dfasdff31
      POSTGRES_USER: origin
    ports:
      - 5432
